const recommend = {
  'UPDATE_BANNER_LIST': 'UPDATE_BANNER_LIST',
  'UPDATE_DISC_LIST': 'UPDATE_DISC_LIST',
}

const singer = {
  'UPDATE_SINGER_LIST': 'UPDATE_SINGER_LIST',
  'UPDATE_SELECTED_SINGER': 'UPDATE_SELECTED_SINGER',
  'UPDATE_SINGER_DETAIL': 'UPDATE_SINGER_DETAIL',
}

export const types = {
  ...recommend,
  ...singer,
}