const recommend = {
  'UPDATE_BANNER_LIST': 'UPDATE_BANNER_LIST',
  'UPDATE_DISC_LIST': 'UPDATE_DISC_LIST',
}

const singer = {
  'UPDATE_SINGER_LIST': 'UPDATE_SINGER_LIST',
  'UPDATE_SELECTED_SINGER': 'UPDATE_SELECTED_SINGER',
  'UPDATE_SINGER_DETAIL': 'UPDATE_SINGER_DETAIL',
}

const song = {
  'UPDATE_SINGER': 'UPDATE_SINGER',
  'UPDATE_PLAYING_STATE': 'UPDATE_PLAYING_STATE',
  'UPDATE_FULL_SCREEN': 'UPDATE_FULL_SCREEN',
  'UPDATE_PLAYLIST': 'UPDATE_PLAYLIST',
  'UPDATE_SEQUENCE_LIST': 'UPDATE_SEQUENCE_LIST',
  'UPDATE_PLAY_MODE': 'UPDATE_PLAY_MODE',
  'UPDATE_CURRENT_INDEX': 'UPDATE_CURRENT_INDEX'
}

export const types = {
  ...recommend,
  ...singer,
  ...song
}